import { forwardRef, useEffect, useImperativeHandle, useMemo, useState } from 'react';
import { api } from '../api';
import type { DiscoveredControl } from '../types';

export interface CurationListHandle {
  saveAll: () => Promise<void>;
}

interface CurationListProps {
  controls: DiscoveredControl[];
  defaultAppId: string;
  /** Called when a row is dismissed and the caller owns a per-control entry to remove (the pick flow) —
   *  when omitted (bulk capture), dismissing just hides the row locally instead. */
  onDismiss?: (controlId: string) => void;
  /** False hides the built-in "Save all" button — the caller drives saving via the forwarded ref
   *  instead (the pick flow wants one Save button in its own toolbar, not one per CurationList). */
  showSaveAll?: boolean;
  /** Reports how many rows are ready to save whenever that changes — only meaningful when
   *  showSaveAll is false, so the caller's own button can reflect the same state. */
  onSaveAllStateChange?: (state: { ready: number; total: number; busy: boolean }) => void;
  /** When set, every saved (or already-saved) row gets a "Use for <field>" action that hands
   *  its name back to the field that requested this capture session — see BL-023 AC4. */
  captureTarget?: { fieldLabel: string; onUse: (name: string) => void };
}

interface RowState {
  name: string;
  label: string;
  appId: string;
  saving: boolean;
  saved: boolean;
  error: string | null;
}

const SHELL_GROUP = 'Launchpad shell (shared across every app)';
const UNGROUPED = 'Ungrouped';

/** "sap.m.GenericTile" -> "GenericTile" — a plain-language object type (link, button, tile...) without the full technical namespace. */
function friendlyType(controlType: string): string {
  return controlType.split('.').pop() || controlType;
}

/** A quick, plain-text guess at what you'd do with this control — not wired into module selection (that's a later story), just enough context to curate sensibly. */
function actionHint(c: DiscoveredControl): string {
  if (c.category === 'informational') return 'Read / assert';
  const t = c.controlType;
  if (/Button|Link|IconTabFilter|GenericTile|Card/.test(t)) return 'Click';
  if (/CheckBox/.test(t)) return 'Toggle';
  if (/RadioButton/.test(t)) return 'Choose';
  if (/Select|ComboBox/.test(t)) return 'Select';
  if (/Date|Time/.test(t)) return 'Pick date';
  if (/Column/.test(t)) return 'Line item field';
  return 'Enter value';
}

/** Walks up the parent chain to the nearest ancestor with real text (a section/panel title) — the group a control visually belongs to on screen. */
function groupLabel(control: DiscoveredControl, byId: Map<string, DiscoveredControl>): string {
  if (control.scope === 'shell') return SHELL_GROUP;
  let current = control.parentId ? byId.get(control.parentId) : undefined;
  while (current) {
    if (current.text) return current.text;
    current = current.parentId ? byId.get(current.parentId) : undefined;
  }
  return UNGROUPED;
}

export const CurationList = forwardRef<CurationListHandle, CurationListProps>(function CurationList(
  { controls, defaultAppId, onDismiss, showSaveAll = true, onSaveAllStateChange, captureTarget },
  ref
) {
  const [existing, setExisting] = useState<Map<string, { appId: string; name: string }>>(new Map());
  const [rows, setRows] = useState<Record<string, RowState>>({});
  const [lookupError, setLookupError] = useState<string | null>(null);
  const [highlighting, setHighlighting] = useState<string | null>(null);
  const [notFoundId, setNotFoundId] = useState<string | null>(null);
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  const byId = useMemo(() => new Map(controls.map((c) => [c.controlId, c])), [controls]);
  // A control with no stable id normally gets classified "structural" (see isAutoGeneratedId)
  // and would silently vanish here — which is worse than useless: a QA engineer Ctrl+Clicks a
  // real, meaningful field (e.g. a generated document-number title) and nothing happens, with
  // no clue why. Surface it anyway, specifically so the warning row below can explain it.
  const visible = useMemo(
    () => controls.filter((c) => (c.category !== 'structural' || c.stableId === false) && !dismissed.has(c.controlId)),
    [controls, dismissed]
  );

  function dismiss(controlId: string) {
    if (onDismiss) onDismiss(controlId);
    else setDismissed((prev) => new Set(prev).add(controlId));
  }

  useEffect(() => {
    let cancelled = false;

    // "Already saved" lookup — checked against both the screen's own app id and the
    // fixed "shell" bucket, so shell controls saved while curating an earlier screen
    // are recognized here instead of being offered up to name again.
    const appIds = Array.from(new Set([defaultAppId, 'shell'].filter(Boolean)));
    Promise.all(appIds.map((id) => api.listObjects(id).catch(() => [])))
      .then((lists) => {
        if (cancelled) return;
        const map = new Map<string, { appId: string; name: string }>();
        lists.forEach((list, i) => list.forEach((o) => map.set(o.controlId, { appId: appIds[i], name: o.name })));
        setExisting(map);
      })
      .catch((e) => !cancelled && setLookupError(String(e)));

    // Only ADD rows for controls that don't have one yet — replacing the whole map here would
    // wipe out in-progress names/labels for controls already being curated every time a new
    // one is added to the list (the pick flow appends to a shared, growing controls array).
    setRows((prev) => {
      let changed = false;
      const next = { ...prev };
      for (const c of visible) {
        if (next[c.controlId]) continue;
        changed = true;
        next[c.controlId] = {
          name: '',
          label: c.text ?? '',
          appId: c.scope === 'shell' ? 'shell' : defaultAppId,
          saving: false,
          saved: false,
          error: null,
        };
      }
      return changed ? next : prev;
    });

    return () => {
      cancelled = true;
    };
  }, [controls, defaultAppId, visible]);

  function updateRow(controlId: string, patch: Partial<RowState>) {
    setRows((prev) => ({ ...prev, [controlId]: { ...prev[controlId], ...patch } }));
  }

  async function highlight(controlId: string) {
    setHighlighting(controlId);
    setNotFoundId(null);
    try {
      const result = await api.highlightControl(controlId);
      if (!result.found) setNotFoundId(controlId);
    } catch {
      setNotFoundId(controlId);
    } finally {
      setHighlighting(null);
    }
  }

  async function save(c: DiscoveredControl) {
    const row = rows[c.controlId];
    if (!row || !row.name.trim()) {
      updateRow(c.controlId, { error: 'Give it a name first.' });
      return;
    }
    updateRow(c.controlId, { saving: true, error: null });
    try {
      // c.tableId (for a table column) is already computed at capture time — see
      // enrichWithTableId in ui5Inspector.ts — so a picked single control carries it
      // just as reliably as a bulk-captured one; fillTableCell/AddLineItem need it
      // paired with the column to drive a specific row during execution.
      await api.saveObject(row.appId, row.name.trim(), {
        controlId: c.controlId,
        controlType: c.controlType,
        bindingPath: c.bindingPath,
        label: row.label || undefined,
        parentControlId: c.parentId,
        tableId: c.tableId,
      });
      updateRow(c.controlId, { saving: false, saved: true, error: null });
      setExisting((prev) => new Map(prev).set(c.controlId, { appId: row.appId, name: row.name.trim() }));
    } catch (e) {
      updateRow(c.controlId, { saving: false, error: String(e) });
    }
  }

  const savableControls = visible.filter((c) => c.stableId !== false && !existing.get(c.controlId) && rows[c.controlId] && !rows[c.controlId].saved);
  const readyToSaveCount = savableControls.filter((c) => rows[c.controlId]?.name.trim()).length;
  const saveAllBusy = savableControls.some((c) => rows[c.controlId]?.saving);

  async function saveAll() {
    for (const c of savableControls) {
      const row = rows[c.controlId];
      if (!row || !row.name.trim() || row.saved) continue;
      await save(c);
    }
  }

  useImperativeHandle(ref, () => ({ saveAll }));

  useEffect(() => {
    onSaveAllStateChange?.({ ready: readyToSaveCount, total: savableControls.length, busy: saveAllBusy });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [readyToSaveCount, savableControls.length, saveAllBusy]);

  if (visible.length === 0) {
    return <p className="hint">Nothing actionable or informational found in this capture.</p>;
  }

  const groups = new Map<string, DiscoveredControl[]>();
  for (const c of visible) {
    const label = groupLabel(c, byId);
    if (!groups.has(label)) groups.set(label, []);
    groups.get(label)!.push(c);
  }
  const orderedGroupNames = Array.from(groups.keys()).sort((a, b) => {
    if (a === SHELL_GROUP) return -1;
    if (b === SHELL_GROUP) return 1;
    if (a === UNGROUPED) return 1;
    if (b === UNGROUPED) return -1;
    return a.localeCompare(b);
  });

  return (
    <div className="stack">
      {lookupError && <p className="error-text">{lookupError}</p>}
      {showSaveAll && savableControls.length > 0 && (
        <div className="row" style={{ alignItems: 'center' }}>
          <button className="primary" disabled={readyToSaveCount === 0 || saveAllBusy} onClick={saveAll}>
            {saveAllBusy ? 'Saving…' : `Save all (${readyToSaveCount})`}
          </button>
          {readyToSaveCount < savableControls.length && (
            <span className="hint">{savableControls.length - readyToSaveCount} still need a name before they'll save.</span>
          )}
        </div>
      )}
      {orderedGroupNames.map((groupName) => (
        <div key={groupName} className="panel stack">
          <p className="section-title">
            {groupName} <span className="hint">({groups.get(groupName)!.length})</span>
          </p>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Control</th>
                  <th>Type</th>
                  <th>Action</th>
                  <th>Name</th>
                  <th>Label</th>
                  <th>App ID</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {groups.get(groupName)!.map((c) => {
                  const already = existing.get(c.controlId);
                  const row = rows[c.controlId];
                  const highlightCell = (
                    <td>
                      <button className="ghost caution" aria-label={`Highlight ${c.text || c.controlType} on screen`} disabled={highlighting === c.controlId} onClick={() => highlight(c.controlId)}>
                        {highlighting === c.controlId ? 'Highlighting…' : 'Highlight on screen'}
                      </button>
                      {notFoundId === c.controlId && <p className="error-text">Not found on screen right now — did you navigate away?</p>}
                    </td>
                  );

                  if (c.stableId === false) {
                    return (
                      <tr key={c.controlId}>
                        <td>{c.text || c.controlType}</td>
                        <td className="hint">{friendlyType(c.controlType)}</td>
                        <td className="hint">{actionHint(c)}</td>
                        <td colSpan={3} className="error-text">
                          No stable id — this control's identifier regenerates on every reload, so saving it would break on the next run. If
                          you're trying to capture a value shown after an action (e.g. a generated document/order number), use "Capture Document
                          Number from Success Dialog" in Compose instead — it reads the confirmation message directly, no capture needed.
                        </td>
                        <td></td>
                        {highlightCell}
                        <td>
                          <button className="ghost neutral" aria-label={`Dismiss ${c.text || c.controlType}`} onClick={() => dismiss(c.controlId)}>
                            Cancel
                          </button>
                        </td>
                      </tr>
                    );
                  }

                  if (already) {
                    return (
                      <tr key={c.controlId}>
                        <td>{c.text || c.controlType}</td>
                        <td className="hint">{friendlyType(c.controlType)}</td>
                        <td className="hint">{actionHint(c)}</td>
                        <td colSpan={3} className="hint">
                          Already saved as &quot;{already.name}&quot; ({already.appId})
                          {captureTarget && (
                            <button className="ghost" style={{ marginLeft: '0.6rem' }} onClick={() => captureTarget.onUse(already.name)}>
                              Use for {captureTarget.fieldLabel}
                            </button>
                          )}
                        </td>
                        <td></td>
                        {highlightCell}
                        <td>
                          <button className="ghost neutral" aria-label={`Dismiss ${c.text || c.controlType}`} onClick={() => dismiss(c.controlId)}>
                            Cancel
                          </button>
                        </td>
                      </tr>
                    );
                  }
                  if (!row) return null;

                  return (
                    <tr key={c.controlId}>
                      <td>{c.text || c.controlType}</td>
                      <td className="hint">{friendlyType(c.controlType)}</td>
                      <td className="hint">{actionHint(c)}</td>
                      <td>
                        <input
                          aria-label={`Object name for ${c.text || c.controlType}`}
                          type="text"
                          value={row.name}
                          placeholder="e.g. SupplierField"
                          disabled={row.saved}
                          onChange={(e) => updateRow(c.controlId, { name: e.target.value })}
                        />
                      </td>
                      <td>
                        <input aria-label={`Object label for ${c.text || c.controlType}`} type="text" value={row.label} disabled={row.saved} onChange={(e) => updateRow(c.controlId, { label: e.target.value })} />
                      </td>
                      <td>
                        <input aria-label={`App ID for ${c.text || c.controlType}`} type="text" value={row.appId} disabled={row.saved} onChange={(e) => updateRow(c.controlId, { appId: e.target.value })} />
                      </td>
                      <td>
                        {row.saving && <span className="hint">Saving…</span>}
                        {row.saved && (
                          <span className="row" style={{ alignItems: 'center', gap: '0.4rem' }}>
                            <span className="badge passed">saved</span>
                            {captureTarget && (
                              <button className="ghost" onClick={() => captureTarget.onUse(row.name.trim())}>
                                Use for {captureTarget.fieldLabel}
                              </button>
                            )}
                          </span>
                        )}
                        {row.error && <p className="error-text">{row.error}</p>}
                      </td>
                      {highlightCell}
                      <td>
                        {!row.saved && (
                          <button className="ghost neutral" aria-label={`Dismiss ${c.text || c.controlType}`} onClick={() => dismiss(c.controlId)}>
                            Cancel
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      ))}
    </div>
  );
});
