import Database from 'better-sqlite3';

export type ControlScope = 'shell' | 'app';
export type VerificationOutcome = 'verified' | 'drifted' | 'missing';
export type VerificationStatus = 'never' | VerificationOutcome;

export interface ControlDefinition {
  appId: string;
  name: string;
  controlId: string;
  bindingPath?: string;
  controlType?: string;
  /**
   * For grid-table (sap.ui.table.Table) cells: the table's own DOM id. When
   * set, controlId holds the column's id rather than a per-cell id, since
   * grid table cells render runtime-generated ids that aren't stable across
   * sessions — see FioriPlaywrightAdapter's tableCell locator.
   */
  tableId?: string;
  /** Human-readable name for evidence captions/reports (e.g. "Delivered Quantity" instead of "DeliveredQuantityColumn"). Falls back to name when unset. */
  label?: string;
  /**
   * The captured UI5 control id of this control's immediate parent, if known — lets the
   * repository represent a screen as a tree (e.g. header section > field) rather than a
   * flat list. Not a foreign key into this table (it's a raw UI5 control id, not a
   * logical `name`) since a parent may not itself be individually named/saved.
   */
  parentControlId?: string;
  /** "shell" (Fiori Launchpad chrome, shared across every app) vs "app" (screen-specific) — see PROJECT_BRIEF_v2.0's scope-tagging note. Unset for rows saved before BL-024 added this column. */
  scope?: ControlScope;
  /** ISO timestamp — set once at first insert, never touched again by upsert(). */
  createdAt?: string;
  /** ISO timestamp of the most recent upsert (capture, edit, or reverify-and-apply). */
  updatedAt?: string;
  /** OS username of whoever last changed this row — see BL-024 AC4 ("attributable"). */
  updatedBy?: string;
  /** ISO timestamp of the most recent reverify attempt, whether or not it changed anything. */
  lastVerifiedAt?: string;
  /** Denormalized outcome of the most recent reverify attempt — "never" until the first one runs. */
  verificationStatus?: VerificationStatus;
}

/** One reverify attempt against a live scan session — kept even when nothing changed, so
 *  "last verified" and its full history are both real facts, not just the current row's
 *  latest snapshot. See BL-024 AC1/AC3. */
export interface VerificationEvent {
  appId: string;
  name: string;
  verifiedAt: string;
  outcome: VerificationOutcome;
  /** The live control matched against, if any (absent when outcome is "missing"). */
  liveControlId?: string;
  liveControlType?: string;
  liveBindingPath?: string;
  liveText?: string;
  verifiedBy?: string;
}

// Mirrors ui5Inspector.ts's isAutoGeneratedId (adapter-fiori) rather than importing it: core
// has zero dependency on adapter-fiori by design (it's the most foundational package), and
// this is a small, self-contained string check — worth duplicating over adding that edge.
const GENERIC_ID_SUFFIXES = new Set(['input', 'inner', 'content', 'edit', 'sfedit', 'sfdisplay']);
const CLONE_SEGMENT_PATTERN = /^__clone\d+$/;

/** True when a stored controlId looks like it will regenerate on the next reload (a per-row
 *  table clone, or an id built entirely from anonymous UI5-generated segments) — see BL-024
 *  AC2's "unstable IDs" health flag. */
export function isLikelyUnstableId(controlId: string): boolean {
  const segments = controlId
    .split(/--|::/)
    .flatMap((s) => s.split('-'))
    .filter((s) => s && !GENERIC_ID_SUFFIXES.has(s.toLowerCase()));
  if (segments.length === 0) return true;
  if (segments.some((s) => CLONE_SEGMENT_PATTERN.test(s))) return true;
  return segments.every((s) => s.startsWith('__'));
}

/** Groups controls sharing the same App ID, type and label under different names — the
 *  closest fact-based proxy for "someone captured the same on-screen element twice" without
 *  a live comparison. Returns a map of name -> the other names it looks like a duplicate of. */
export function findLikelyDuplicates(controls: Pick<ControlDefinition, 'name' | 'controlType' | 'label'>[]): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  for (const c of controls) {
    if (!c.controlType || !c.label) continue; // too little to compare on safely
    // \0 (not a plain space) so a controlType/label that itself contains a space can never
    // collide with a different type/label split at the wrong point.
    const key = `${c.controlType}\0${c.label}`;
    groups.set(key, [...(groups.get(key) ?? []), c.name]);
  }
  const result = new Map<string, string[]>();
  for (const names of groups.values()) {
    if (names.length < 2) continue;
    for (const name of names) result.set(name, names.filter((n) => n !== name));
  }
  return result;
}

/**
 * Reusable repository of UI control definitions, keyed by (appId, logical name).
 * Modules look up controls by logical name so a screen change only requires
 * updating the entry here, not every test case that uses it.
 */
export class ObjectRepository {
  private db: Database.Database;

  constructor(dbPath: string) {
    this.db = new Database(dbPath);
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS controls (
        app_id TEXT NOT NULL,
        name TEXT NOT NULL,
        control_id TEXT NOT NULL,
        binding_path TEXT,
        control_type TEXT,
        table_id TEXT,
        label TEXT,
        parent_control_id TEXT,
        PRIMARY KEY (app_id, name)
      )
    `);
    for (const migration of [
      'ALTER TABLE controls ADD COLUMN table_id TEXT',
      'ALTER TABLE controls ADD COLUMN label TEXT',
      'ALTER TABLE controls ADD COLUMN parent_control_id TEXT',
      'ALTER TABLE controls ADD COLUMN sort_order INTEGER',
      'ALTER TABLE controls ADD COLUMN scope TEXT',
      'ALTER TABLE controls ADD COLUMN created_at TEXT',
      'ALTER TABLE controls ADD COLUMN updated_at TEXT',
      'ALTER TABLE controls ADD COLUMN updated_by TEXT',
      'ALTER TABLE controls ADD COLUMN last_verified_at TEXT',
      "ALTER TABLE controls ADD COLUMN verification_status TEXT DEFAULT 'never'",
    ]) {
      try {
        this.db.exec(migration);
      } catch {
        // column already exists on a repository created before this field was added
      }
    }
    /**
     * Where an App ID's controls were captured from.
     *
     * The scan session already knows this — it holds the session URL and returns `pageUrl` with
     * every capture — but it was thrown away, so an author who had just captured twelve controls
     * from a screen still had to retype that screen's URL from memory into NavigateToApp. It was
     * the single most expensive field in the 16-step Sales Order build: 39s of a modelled 353s,
     * nearly 29s of it typing 103 characters.
     *
     * Many rows per app_id, deliberately: an App ID is a scope of captured controls and one
     * scope legitimately spans several Fiori screens. create-delivery navigates to
     * OutboundDelivery-createFromDueList and then OutboundDelivery-pick under a single App ID,
     * so a one-URL-per-app mapping would have quietly sent it to the wrong screen.
     */
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS app_entry_points (
        app_id TEXT NOT NULL,
        url TEXT NOT NULL,
        first_seen_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        PRIMARY KEY (app_id, url)
      )
    `);
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS object_verifications (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        app_id TEXT NOT NULL,
        name TEXT NOT NULL,
        verified_at TEXT NOT NULL,
        outcome TEXT NOT NULL,
        live_control_id TEXT,
        live_control_type TEXT,
        live_binding_path TEXT,
        live_text TEXT,
        verified_by TEXT
      )
    `);
  }

  upsert(def: ControlDefinition, updatedBy?: string): void {
    const now = new Date().toISOString();
    // better-sqlite3's named-parameter binding requires every key the SQL references to be
    // present on the bound object, even as null — a ControlDefinition only guarantees its
    // required fields, so this normalizes every optional one explicitly rather than relying
    // on each caller to remember to spread in a full set of undefined placeholders.
    const bound = {
      appId: def.appId,
      name: def.name,
      controlId: def.controlId,
      bindingPath: def.bindingPath ?? null,
      controlType: def.controlType ?? null,
      tableId: def.tableId ?? null,
      label: def.label ?? null,
      parentControlId: def.parentControlId ?? null,
      scope: def.scope ?? null,
      createdAt: def.createdAt ?? now,
      updatedAt: now,
      updatedBy: updatedBy ?? null,
    };
    this.db
      .prepare(
        `INSERT INTO controls (app_id, name, control_id, binding_path, control_type, table_id, label, parent_control_id, scope, created_at, updated_at, updated_by)
         VALUES (@appId, @name, @controlId, @bindingPath, @controlType, @tableId, @label, @parentControlId, @scope, @createdAt, @updatedAt, @updatedBy)
         ON CONFLICT(app_id, name) DO UPDATE SET
           control_id = excluded.control_id,
           binding_path = excluded.binding_path,
           control_type = excluded.control_type,
           table_id = excluded.table_id,
           label = excluded.label,
           parent_control_id = excluded.parent_control_id,
           scope = excluded.scope,
           updated_at = excluded.updated_at,
           updated_by = excluded.updated_by`
        // created_at is deliberately absent from the UPDATE SET list above — on conflict,
        // whatever the row's created_at already was stays untouched; the @createdAt bound
        // here only ever lands on a genuine first insert.
      )
      .run(bound);
  }

  private static readonly SELECT_COLUMNS = `
    app_id as appId, name, control_id as controlId, binding_path as bindingPath, control_type as controlType,
    table_id as tableId, label, parent_control_id as parentControlId, scope,
    created_at as createdAt, updated_at as updatedAt, updated_by as updatedBy,
    last_verified_at as lastVerifiedAt, verification_status as verificationStatus`;

  get(appId: string, name: string): ControlDefinition {
    const row = this.db
      .prepare(`SELECT ${ObjectRepository.SELECT_COLUMNS} FROM controls WHERE app_id = ? AND name = ?`)
      .get(appId, name) as ControlDefinition | undefined;

    if (!row) {
      throw new Error(
        `Object repository: no control named "${name}" for app "${appId}". ` +
          `Run "taf inspect" against the live screen, then "taf objects add" to seed it.`
      );
    }
    return row;
  }

  /** Every App ID that has at least one saved object — lets Studio show what already exists before a new one gets captured. */
  listAppIds(): string[] {
    return (this.db.prepare('SELECT DISTINCT app_id as appId FROM controls ORDER BY app_id').all() as { appId: string }[]).map(
      (r) => r.appId
    );
  }

  listByApp(appId: string): ControlDefinition[] {
    return this.db
      .prepare(
        `SELECT ${ObjectRepository.SELECT_COLUMNS} FROM controls WHERE app_id = ?
         ORDER BY sort_order IS NULL, sort_order ASC, rowid ASC`
      )
      .all(appId) as ControlDefinition[];
  }

  /** Appends one reverify attempt to the permanent history and updates the control's own
   *  denormalized last-verified snapshot — recorded even when the outcome changes nothing,
   *  so "last verified" is always a real fact, not just implied by an unrelated edit. */
  recordVerification(event: VerificationEvent): void {
    this.db
      .prepare(
        `INSERT INTO object_verifications (app_id, name, verified_at, outcome, live_control_id, live_control_type, live_binding_path, live_text, verified_by)
         VALUES (@appId, @name, @verifiedAt, @outcome, @liveControlId, @liveControlType, @liveBindingPath, @liveText, @verifiedBy)`
      )
      .run({
        ...event,
        liveControlId: event.liveControlId ?? null,
        liveControlType: event.liveControlType ?? null,
        liveBindingPath: event.liveBindingPath ?? null,
        liveText: event.liveText ?? null,
        verifiedBy: event.verifiedBy ?? null,
      });
    this.db
      .prepare('UPDATE controls SET last_verified_at = ?, verification_status = ? WHERE app_id = ? AND name = ?')
      .run(event.verifiedAt, event.outcome, event.appId, event.name);
  }

  /** Every recorded verification attempt for one control, most recent first. */
  listVerifications(appId: string, name: string): VerificationEvent[] {
    return this.db
      .prepare(
        `SELECT app_id as appId, name, verified_at as verifiedAt, outcome, live_control_id as liveControlId,
                live_control_type as liveControlType, live_binding_path as liveBindingPath, live_text as liveText, verified_by as verifiedBy
         FROM object_verifications WHERE app_id = ? AND name = ? ORDER BY id DESC`
      )
      .all(appId, name) as VerificationEvent[];
  }

  /** Persists a user-chosen display order for an App ID's objects (drag-and-drop reordering in
   * Studio's Object Browser) — names not present in `orderedNames` (shouldn't normally happen,
   * but a stale client request is possible) keep whatever order they already had, sorting after
   * every explicitly-ordered name. */
  reorder(appId: string, orderedNames: string[]): void {
    const update = this.db.prepare('UPDATE controls SET sort_order = ? WHERE app_id = ? AND name = ?');
    const applyAll = this.db.transaction(() => {
      orderedNames.forEach((name, index) => update.run(index, appId, name));
    });
    applyAll();
  }

  /** Permanently removes one saved object — there is no undo. */
  remove(appId: string, name: string): void {
    this.db.prepare('DELETE FROM controls WHERE app_id = ? AND name = ?').run(appId, name);
  }

  /** Permanently removes all saved objects and verifications for an App ID — there is no undo. */
  removeAppId(appId: string): void {
    this.db.prepare('DELETE FROM object_verifications WHERE app_id = ?').run(appId);
    this.db.prepare('DELETE FROM app_entry_points WHERE app_id = ?').run(appId);
    this.db.prepare('DELETE FROM controls WHERE app_id = ?').run(appId);
  }

  /**
   * Notes that this App ID's controls were captured from `url`. Called when a scanned control is
   * saved, so the entry point is learned as a side effect of ordinary capture rather than being
   * another thing to maintain. Re-capturing from the same screen refreshes lastSeenAt only.
   */
  recordEntryPoint(appId: string, url: string): void {
    const trimmed = url.trim();
    if (!appId.trim() || !trimmed) return;
    const now = new Date().toISOString();
    this.db
      .prepare(
        `INSERT INTO app_entry_points (app_id, url, first_seen_at, last_seen_at)
         VALUES (@appId, @url, @now, @now)
         ON CONFLICT(app_id, url) DO UPDATE SET last_seen_at = @now`
      )
      .run({ appId, url: trimmed, now });
  }

  /** Known entry points for an App ID, most recently seen first. */
  listEntryPoints(appId: string): { url: string; firstSeenAt: string; lastSeenAt: string }[] {
    return this.db
      .prepare(
        `SELECT url, first_seen_at AS firstSeenAt, last_seen_at AS lastSeenAt
         FROM app_entry_points WHERE app_id = ? ORDER BY last_seen_at DESC`
      )
      .all(appId) as { url: string; firstSeenAt: string; lastSeenAt: string }[];
  }

  /** Renames a saved object in place, keeping everything else (controlId, label, tableId,
   * createdAt, verification history...) — since the table's primary key is (app_id, name),
   * this is an insert-under-the-new-name-then-delete-the-old, not a column update, but
   * callers don't need to care about that distinction. */
  rename(appId: string, oldName: string, newName: string, updatedBy?: string): void {
    if (oldName === newName) return;
    const def = this.get(appId, oldName);
    this.upsert({ ...def, name: newName }, updatedBy);
    this.db.prepare('UPDATE object_verifications SET name = ? WHERE app_id = ? AND name = ?').run(newName, appId, oldName);
    this.remove(appId, oldName);
  }

  close(): void {
    this.db.close();
  }
}
