import { Frame, Page } from 'playwright';

export type ControlCategory = 'actionable' | 'informational' | 'structural';
export type ControlScope = 'shell' | 'app';

export interface DiscoveredControl {
  controlId: string;
  controlType: string;
  bindingPath?: string;
  text?: string;
  /** The id of this control's immediate UI5 parent, if any — lets the object repository store screens as a tree instead of a flat list. */
  parentId?: string;
  /** A rough, deterministic guess at whether this control is worth a human's attention — see classifyControl. */
  category: ControlCategory;
  /**
   * "shell": part of the Fiori Launchpad chrome (global search, notifications, home,
   * user menu) that wraps every app and is identical regardless of which one is open —
   * as opposed to "app", content specific to whatever screen was captured. Detected by
   * namespace, not by comparing captures, so it's meaningful even on the very first scan.
   */
  scope: ControlScope;
  /**
   * For a table Column (sap.ui.table.Column/sap.m.Column), the enclosing table's own
   * control id — the pairing fillTableCell/AddLineItem need to drive a specific row
   * during execution, since individual row cells render unstable "clone" ids. Computed
   * once here (a column's immediate parent is the table itself) so it's available
   * whether the column was bulk-captured or picked individually — a picked control only
   * ever carries itself to the client, with no sibling data to derive this from later.
   */
  tableId?: string;
  /**
   * False when this control's id is purely auto-generated (e.g. "__title38") — regenerates
   * on every page reload/navigation (a fresh incrementing counter), so saving it into the
   * object repository would look fine today and silently break on the very next run. See
   * isAutoGeneratedId — the same rule that already forces a per-row table clone to
   * "structural" also flags a control like this, but a genuinely singular, meaningful
   * control (an Object Page's generated title) can still be actionable/informational
   * *and* have no stable id at the same time, so this is surfaced as its own flag rather
   * than folded into category.
   */
  stableId: boolean;
}

/** Namespace families that belong to the Launchpad shell itself, not to any one app — see ControlScope. */
function classifyScope(controlType: string): ControlScope {
  if (controlType.startsWith('sap.ushell.')) return 'shell';
  if (controlType.includes('ShellBar')) return 'shell';
  return 'app';
}

// A real Fiori screen commonly nests one meaningful control (a button, a field) under
// several layers of pure layout scaffolding (toolbars, boxes, pages, views) that no test
// will ever act on directly — that scaffolding is most of what makes a raw scan feel like
// noise. This list is a deliberate starting point, not an exhaustive taxonomy of every
// UI5 control type; expect to tune it as more real screens get scanned.
const ACTIONABLE_TYPES = new Set([
  'sap.m.Button',
  'sap.m.OverflowToolbarButton',
  'sap.m.MenuButton',
  'sap.m.SplitButton',
  'sap.m.Link',
  'sap.m.Input',
  'sap.m.SearchField',
  'sap.m.TextArea',
  'sap.m.Select',
  'sap.m.ComboBox',
  'sap.m.MultiComboBox',
  'sap.m.CheckBox',
  'sap.m.RadioButton',
  'sap.m.RadioButtonGroup',
  'sap.m.DatePicker',
  'sap.m.DateTimePicker',
  'sap.m.TimePicker',
  'sap.m.Switch',
  'sap.m.StepInput',
  'sap.m.IconTabFilter', // a tab a user clicks — actionable despite living inside a structural IconTabBar
  'sap.ui.table.Column',
  'sap.m.Column',
  // Launchpad home-page tiles — clicking one navigates to an app. Its own getText()/bindingPath
  // are typically empty (the visible title lives in a child sap.m.Text/TileContent instead), so
  // without an explicit entry here it fell through to structural. Found via a real capture, not
  // guessed up front — clicking "Manage Purchase Orders" resolved to nothing actionable before this.
  'sap.m.GenericTile',
  'sap.f.Card', // the newer card-based tile layout some Launchpads use instead of GenericTile — not yet seen on this tenant, added on the same reasoning
  // A SmartFilterBar's own field controls (the search bar on a List Report screen) — real,
  // stable ids, just a type this list hadn't covered yet. Their whole container chain
  // (SmartFilterBarFilterGroupItem, SmartFilterBar, DynamicPageHeader...) is legitimately
  // structural too, so without these entries the ancestor-preference walk found nothing
  // actionable anywhere and fell back to the innermost element. Found via a real capture on
  // the Manage Purchase Orders screen, not guessed up front.
  'sap.ui.comp.smartfilterbar.SFBSearchField',
  'sap.ui.comp.smartfilterbar.SFBMultiInput',
  'sap.m.internal.DynamicDateRangeInput',
  // The newer "MDC" (metadata-driven controls) framework some Fiori Elements v4 apps use
  // instead of classic sap.m.Input/DatePicker/etc. — same fillable-field role, different
  // control type. Found via a real capture on the Manage Sales Orders V2 app's Create
  // dialog (Sales Order Type/Org/Distribution Channel/Division all render as this type),
  // not guessed up front.
  'sap.ui.mdc.Field',
]);

const INFORMATIONAL_TYPES = new Set([
  'sap.m.Text',
  'sap.m.Label',
  'sap.m.Title',
  'sap.m.ObjectStatus',
  'sap.m.ObjectNumber',
  'sap.m.MessageStrip',
]);

// Always structural regardless of text/bindingPath — these carry a "text" property for
// screen-reader purposes only (ARIA labeling like "Toggle header") and are never visible
// or actionable, so the generic "has text" fallback below would otherwise wrongly
// promote them to informational. Found via a real capture, not guessed up front.
//
// sap.ui.core.ComponentContainer and sap.ui.core.mvc.XMLView are here for a related but
// distinct reason: each hosts an entire nested view/page, so it inherits that page's
// bindingPath (the whole bound entity) without itself displaying any single value — the
// generic "has a bindingPath" rule below would otherwise call it "informational" purely
// because of that inherited context. Since view/component-hosting wrappers like these sit
// near the OUTERMOST end of almost every ancestor chain, "prefer the outermost informational
// match" then picks the wrapper over the actual field/title you clicked, every time. Found
// via a real capture: Ctrl+Clicking an Object Page's own title (a stable sap.m.Title)
// resolved to a ComponentContainer first, then — after excluding that — to the XMLView
// hosting it instead. Both are "this represents an entire view", never real content, so any
// future case in the same family (another sap.ui.core.mvc.View subtype, etc.) belongs here too.
const ALWAYS_STRUCTURAL_TYPES = new Set(['sap.ui.core.InvisibleText', 'sap.ui.core.ComponentContainer', 'sap.ui.core.mvc.XMLView']);

// UI5 internal sub-control suffixes that carry no semantic meaning of their own (a SmartField's
// edit-mode inner control, an Input's native <input>, etc.) — ignored when judging whether an id
// has any real, human-assigned segment.
const GENERIC_ID_SUFFIXES = new Set(['input', 'inner', 'content', 'edit', 'sfedit', 'sfdisplay']);

/**
 * Grid/smart tables clone a template control per visible row — e.g.
 * "__field18-__clone549-sfEdit-input" — rather than reusing the column's one stable id
 * (already captured separately as a sap.ui.table.Column/sap.m.Column). Every segment of
 * a purely auto-generated id starts with "__" and carries an incrementing counter, not a
 * human-assigned name; a real control's id always has at least one segment that doesn't.
 * These ids are also inherently unstable — the same field can get a different "__cloneNNN"
 * suffix after a reload or a different row count — so they're unsuitable for the object
 * repository regardless of how many of them there are. Found via a real capture (a 13-column
 * table was surfacing 90 "sap.m.Input" rows before this), not guessed up front.
 *
 * A response table's row-select checkbox showed the opposite shape of the same problem:
 * "...ColumnListItem-__clone178-selectMulti" — a real, human-assigned prefix AND suffix
 * segment, with the per-row "__cloneNNN" marker buried in the middle rather than being the
 * whole id. The "every segment starts with __" rule above missed this entirely (most
 * segments look genuine), so it got saved as a normal object and broke on the very next run
 * when the clone counter changed. "__cloneNNN" is a deliberate, specific marker UI5 only
 * ever uses for a per-row template clone — its mere presence anywhere in the id means the
 * whole id is unstable, regardless of what else surrounds it.
 */
const CLONE_SEGMENT_PATTERN = /^__clone\d+$/;

function isAutoGeneratedId(controlId: string): boolean {
  const segments = controlId
    .split(/--|::/)
    .flatMap((s) => s.split('-'))
    .filter((s) => s && !GENERIC_ID_SUFFIXES.has(s.toLowerCase()));
  if (segments.length === 0) return true;
  if (segments.some((s) => CLONE_SEGMENT_PATTERN.test(s))) return true;
  return segments.every((s) => s.startsWith('__'));
}

// The auto-generated-id check exists to catch per-row table clones (many near-identical
// instances of the same field, none individually stable) — but Launchpad tiles (and the
// Fiori "MyHome" category-tab tiles specifically) are genuinely singular, meaningful
// controls that also happen to get short auto-ids like "__tile161" as their normal
// convention, not as a symptom of row-cloning. Without this exemption, a real tile got
// forced to structural, and every other tile on that same tab's ancestor-walk then
// resolved to the same shared Page/Section container instead — so only the first pick
// ever registered (later ones deduped against that identical shared id). Found via a real
// capture on the Procurement category tab, not guessed up front.
const AUTO_ID_EXEMPT_TYPES = new Set(['sap.m.GenericTile', 'sap.f.Card']);

/** Deterministically guesses whether a captured control is worth showing by default — see the module comment above ACTIONABLE_TYPES. */
export function classifyControl(c: Pick<DiscoveredControl, 'controlId' | 'controlType' | 'text' | 'bindingPath'>): ControlCategory {
  if (ALWAYS_STRUCTURAL_TYPES.has(c.controlType)) return 'structural';
  if (!AUTO_ID_EXEMPT_TYPES.has(c.controlType) && isAutoGeneratedId(c.controlId)) return 'structural';
  if (ACTIONABLE_TYPES.has(c.controlType)) return 'actionable';
  if (INFORMATIONAL_TYPES.has(c.controlType) || c.text || c.bindingPath) return 'informational';
  return 'structural';
}

// Controls whose own getText()/getTitle()/getHeaderText() is reliably empty because the visible
// title lives in a nested child control instead — a GenericTile's title is a separate sap.m.Text
// child, not a property of the tile itself. Found via a real capture (a picked "Manage Purchase
// Orders" tile showed a blank Label — its own text really is empty; the name is one level down).
// Scoped to this specific, known set rather than applied to every text-less control, and applied
// only AFTER classification below, so borrowing a child's text never changes what counts as
// structural — it only improves what gets displayed/suggested as a label.
const BORROWS_CHILD_TEXT = new Set(['sap.m.GenericTile', 'sap.f.Card', 'sap.ui.table.Column', 'sap.m.Column']);

function enrichWithChildText(controls: DiscoveredControl[]): DiscoveredControl[] {
  const childrenByParent = new Map<string, DiscoveredControl[]>();
  for (const c of controls) {
    if (!c.parentId) continue;
    if (!childrenByParent.has(c.parentId)) childrenByParent.set(c.parentId, []);
    childrenByParent.get(c.parentId)!.push(c);
  }
  return controls.map((c) => {
    if (c.text || !BORROWS_CHILD_TEXT.has(c.controlType)) return c;
    const childWithText = (childrenByParent.get(c.controlId) ?? []).find((child) => child.text);
    return childWithText ? { ...c, text: childWithText.text } : c;
  });
}

const TABLE_COLUMN_TYPES = new Set(['sap.ui.table.Column', 'sap.m.Column']);
const TABLE_CONTAINER_TYPES = new Set(['sap.ui.table.Table', 'sap.m.Table']);

/** A column's immediate parent is the table itself (confirmed on a real grid table) — see DiscoveredControl.tableId. */
function enrichWithTableId(controls: DiscoveredControl[]): DiscoveredControl[] {
  const byId = new Map(controls.map((c) => [c.controlId, c]));
  return controls.map((c) => {
    if (!TABLE_COLUMN_TYPES.has(c.controlType) || !c.parentId) return c;
    const parent = byId.get(c.parentId);
    return parent && TABLE_CONTAINER_TYPES.has(parent.controlType) ? { ...c, tableId: parent.controlId } : c;
  });
}

/** What inspectFrame can determine from inside the page — classification happens back in Node, after evaluate() returns. */
type RawDiscoveredControl = Omit<DiscoveredControl, 'category' | 'scope' | 'stableId'>;

async function inspectFrame(frame: Frame): Promise<RawDiscoveredControl[]> {
  return frame.evaluate(() => {
    const core = (window as any).sap?.ui?.getCore?.();
    if (!core || typeof core.byId !== 'function') return [];

    // Enumerate via the public byId() API against every DOM id present, rather than
    // relying on private registry internals (getElementRegistry/_uiElements), which
    // vary across UI5 versions and were silently returning nothing on this tenant.
    const ids = new Set<string>();
    document.querySelectorAll('[id]').forEach((el) => ids.add(el.id));

    // A screen's meaningful section/panel headings are as often exposed via getTitle()/
    // getHeaderText() as getText() — a Panel or ObjectPageSection's own "text" is empty,
    // its title lives under a differently-named getter. Trying only getText() left most
    // real section names undetected (found by checking real captured output, not guessed).
    function extractText(c: any): string | undefined {
      for (const getter of ['getText', 'getTitle', 'getHeaderText']) {
        if (typeof c[getter] !== 'function') continue;
        const value = c[getter]();
        if (typeof value === 'string' && value) return value;
      }
      return undefined;
    }

    // The Fiori Launchpad keeps a previously-opened app's whole UI5 component alive in the
    // DOM (hidden, not destroyed) after navigating to a different app — a standard "keep
    // alive" performance pattern, not a bug in the tenant. document.querySelectorAll('[id]')
    // finds these stale elements right alongside the real, currently-visible screen's own
    // controls, with no way to tell them apart by id or type alone. Found via a real capture
    // on this tenant: after navigating Launchpad home -> Procurement -> Process Purchase
    // Requisitions, the capture still contained 40 sap.m.GenericTile controls from the Home
    // page (bound for "homeApp-component---myhome--..."), none of them destroyed, all still
    // resolving through core.byId(). Filtering to only elements actually rendered on screen —
    // not display:none, not inside a hidden ancestor — excludes stale kept-alive components
    // regardless of which app they belong to, without needing to know their ids up front.
    function isRendered(el: HTMLElement | null | undefined): boolean {
      if (!el) return true; // no DOM element at all — a logical-only control, not something to filter here
      return el.offsetParent !== null || el.getClientRects().length > 0;
    }

    const controls: RawDiscoveredControl[] = [];
    ids.forEach((id) => {
      const control = core.byId(id);
      if (!control) return;
      if (!isRendered(typeof control.getDomRef === 'function' ? control.getDomRef() : undefined)) return;
      const bindingContext = typeof control.getBindingContext === 'function' ? control.getBindingContext() : undefined;
      const parent = typeof control.getParent === 'function' ? control.getParent() : undefined;
      controls.push({
        controlId: control.getId?.() ?? id,
        controlType: control.getMetadata?.().getName?.() ?? 'unknown',
        bindingPath: bindingContext?.getPath?.(),
        text: extractText(control),
        parentId: parent?.getId?.(),
      });
    });
    return controls;
  });
}

/**
 * Enumerates live UI5 controls across the page and any embedded iframes —
 * Fiori Launchpad apps commonly render inside one — used to seed the object
 * repository for a screen. Only applicable to actual UI5-rendered frames; a
 * plain HTML login page (e.g. an external IdP) has no UI5 runtime and must be
 * inspected with ordinary browser devtools instead.
 */
export async function inspectUi5Controls(page: Page): Promise<DiscoveredControl[]> {
  const perFrame = await Promise.all(page.frames().map((frame) => inspectFrame(frame).catch(() => [] as RawDiscoveredControl[])));
  const classified = perFrame
    .flat()
    .map((c) => ({ ...c, category: classifyControl(c), scope: classifyScope(c.controlType), stableId: !isAutoGeneratedId(c.controlId) }));
  return enrichWithTableId(enrichWithChildText(classified));
}
